"""add_token_acesso_simulado_table

Revision ID: 7823d8307ec0
Revises: 3271322a4933
Create Date: 2025-12-03 18:51:03.737726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7823d8307ec0'
down_revision: Union[str, None] = '3271322a4933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
