"""refactor_saeb_v2_move_attributes_to_questao

Revision ID: 98036d68aa5d
Revises: bf5ed16780d2
Create Date: 2025-12-02 06:30:48.942854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98036d68aa5d'
down_revision: Union[str, None] = 'bf5ed16780d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add columns to questoes_saeb with temporary names first
    op.add_column('questoes_saeb', sa.Column('ano_escolar', sa.Integer(), nullable=True))

    # Update ano_escolar with values from descritor (join)
    op.execute("""
        UPDATE questoes_saeb q
        SET ano_escolar = d.ano_escolar
        FROM descritores_saeb d
        WHERE q.descritor_id = d.id
    """)

    # Make ano_escolar NOT NULL
    op.alter_column('questoes_saeb', 'ano_escolar', nullable=False)

    # Add disciplina column using existing enum
    op.add_column('questoes_saeb', sa.Column('disciplina', postgresql.ENUM('portugues', 'matematica', name='disciplinasaeb'), nullable=True))

    # Update disciplina with values from descritor
    op.execute("""
        UPDATE questoes_saeb q
        SET disciplina = d.disciplina
        FROM descritores_saeb d
        WHERE q.descritor_id = d.id
    """)

    # Make disciplina NOT NULL
    op.alter_column('questoes_saeb', 'disciplina', nullable=False)

    # Add bloco column using existing enum
    op.add_column('questoes_saeb', sa.Column('bloco', postgresql.ENUM('1', '2', name='blocosaeb'), nullable=True))

    # Update bloco with values from descritor
    op.execute("""
        UPDATE questoes_saeb q
        SET bloco = d.bloco::text::blocosaeb
        FROM descritores_saeb d
        WHERE q.descritor_id = d.id
    """)

    # Make bloco NOT NULL
    op.alter_column('questoes_saeb', 'bloco', nullable=False)

    # Now drop columns from descritores_saeb
    op.drop_column('descritores_saeb', 'ano_escolar')
    op.drop_column('descritores_saeb', 'disciplina')
    op.drop_column('descritores_saeb', 'bloco')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questoes_saeb', 'ano_escolar')
    op.drop_column('questoes_saeb', 'bloco')
    op.drop_column('questoes_saeb', 'disciplina')
    op.add_column('descritores_saeb', sa.Column('bloco', postgresql.ENUM('BLOCO_1', 'BLOCO_2', name='blocosaeb'), autoincrement=False, nullable=False))
    op.add_column('descritores_saeb', sa.Column('disciplina', postgresql.ENUM('PORTUGUES', 'MATEMATICA', name='disciplinasaeb'), autoincrement=False, nullable=False))
    op.add_column('descritores_saeb', sa.Column('ano_escolar', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
