"""Add SAEB V2 models

Revision ID: bf5ed16780d2
Revises: 
Create Date: 2025-12-02 05:35:56.830755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5ed16780d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if ENUM type exists and create if not
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE prioridademensagem AS ENUM ('BAIXA', 'NORMAL', 'ALTA', 'URGENTE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Remove default value before conversion
    op.execute("ALTER TABLE mensagens ALTER COLUMN prioridade DROP DEFAULT")

    # Convert column type with USING clause
    op.execute("""
        ALTER TABLE mensagens
        ALTER COLUMN prioridade TYPE prioridademensagem
        USING CASE
            WHEN prioridade = 'baixa' THEN 'BAIXA'::prioridademensagem
            WHEN prioridade = 'normal' THEN 'NORMAL'::prioridademensagem
            WHEN prioridade = 'alta' THEN 'ALTA'::prioridademensagem
            WHEN prioridade = 'urgente' THEN 'URGENTE'::prioridademensagem
            ELSE 'NORMAL'::prioridademensagem
        END
    """)

    # Set new default value
    op.execute("ALTER TABLE mensagens ALTER COLUMN prioridade SET DEFAULT 'NORMAL'::prioridademensagem")

    op.create_foreign_key(None, 'turmas', 'professores', ['professor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turmas', type_='foreignkey')
    op.alter_column('mensagens', 'prioridade',
               existing_type=sa.Enum('BAIXA', 'NORMAL', 'ALTA', 'URGENTE', name='prioridademensagem'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    # ### end Alembic commands ###
